---
- name: Install package
  become: True
  package:
    name: kubernetes-hyperkube-kube-apiserver
    state: present
    update_cache: True

- name: Configure package
  become: True
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: kube-apiserver.j2
      dest: /etc/default/kube-apiserver
    - src: systemd.service.j2
      dest: /etc/systemd/system/kube-apiserver.service
  notify:
    - Reload systemd
    - Restart kube-apiserver
